### ISSUE TITLE
Syntax error tLABEL  using ruby 1.9.1

### ISSUE THREAD

**Issue by wwright2** [datafolklabs/ruby-parseconfig#31]
ruby 1.9.3p547 (2014-05-14 revision 45962) [arm-linux-eabi]

```
main.rb:5:in `require': /usr/lib/ruby/gems/1.9.1/gems/parseconfig-1.0.7/lib/parseconfig.rb:31: syntax error, unexpected tLABEL (SyntaxError)
  def initialize(config_file=nil, separator='=', comments: ['#', ';'])
                                                           ^
/usr/lib/ruby/gems/1.9.1/gems/parseconfig-1.0.7/lib/parseconfig.rb:31: syntax error, unexpected ')', expecting keyword_end
/usr/lib/ruby/gems/1.9.1/gems/parseconfig-1.0.7/lib/parseconfig.rb:208: syntax error, unexpected keyword_end, expecting $end
        from main.rb:5:in `<main>'
```

---
I changed 
    comments: ['#', ';']
to
 comments= ['#', ';']

Which seems to fix my issue....but I am sure there is an explanation, I just don't see it, thx.

**Comment by derks** [comment]
Looks like an incompatibility with Ruby < 2.0 (named positional arguments).  Going to switch `comments: ['#', ';']` to `comments=['#', ';']` like you mentioned as we don't want to break backward compatibility in `stable/1.0.x` and this a new feature.

Thank you for the report.

**Comment by derks** [comment]
@wwright2 you got the above syntax error just by requiring `parseconfig`?  Unsure why Travis CI tests passed on 1.8 and 1.9 then...

**Comment by derks** [comment]
Thanks for the feedback.  Pushing out 1.0.8.

**Comment by wwright2** [comment]
Thanks.  Checked out and using 1.0.8.
